name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SOLUTION_PATH: src/SpatialLITE.sln

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    
    - name: Install dotnet-format
      run: dotnet tool install -g dotnet-format

    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_PATH }}
      
    - name: Check code format
      run: dotnet format ${{ env.SOLUTION_PATH }} --no-restore --verify-no-changes
      
    - name: Build
      run: dotnet build ${{ env.SOLUTION_PATH }} --no-restore
    
    - name: Download Osmium
      run: apt-get install osmium-tool --quiet --yes
        
    - name: Test
      run: dotnet test ${{ env.SOLUTION_PATH }} --no-build --verbosity normal
