name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SOLUTION_PATH: src/SpatialLITE.sln

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    
    - name: Install dotnet-format
      run: dotnet tool install -g dotnet-format

    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_PATH }}
      
    - name: Check code format
      run: dotnet format ${{ env.SOLUTION_PATH }} --no-restore --verify-no-changes
      
    - name: Build
      run: dotnet build ${{ env.SOLUTION_PATH }} --no-restore
    
    - name: Make Osmium executable (if present)
      run: |
        if [ -f src/Tests/SpatialLITE.IntegrationTests/bin/Debug/net8.0/Tools/Osmium/Linux/osmium ]; then
          chmod +x src/Tests/SpatialLITE.IntegrationTests/bin/Debug/net8.0/Tools/Osmium/Linux/osmium
          echo "Osmium binary found"
        else
          echo "Osmium binary not found, integration tests may fail"
        fi
        
    - name: Test
      run: dotnet test ${{ env.SOLUTION_PATH }} --no-build --verbosity normal --logger:"trx"

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: '**/TestResults/*.trx'
